title: Hopefully useful articles about programming by Manish Kumar
author: Manish Kumar
email: manish.bansal@gmail.com
description: >
  This is a place where I share my thoughts with the world.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: manishkumar03
  url: https://github.com/manishkumar03
  icon: icon-github.svg
- username: BansalToronto
  url: https://twitter.com/BansalToronto
  icon: icon-twitter.svg

paginate: 5

markdown: kramdown

kramdown:
  hard_wrap: true
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
